apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-crawler
  labels:
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: where-for-dinner
spec:
  params:
  - name: annotations
    value: 
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/Albertoimpl/where-for-dinner.git
      ref:
        branch: main
    subPath: where-for-dinner-crawler